### ISSUE TITLE
Feature Request: Add Invert colors option.

### ISSUE THREAD

**Issue by PyGamer0** [mswift42/themecreator#15]

**Comment by mswift42** [comment]
Sorry, but I'm not going to add this. 

If you want to see how a theme looks with inverted colors, you can install a browser extension (like [invert colors](https://github.com/Max-Github/FireFoxInvertColors)).

If you want to make a dark / light variant of a color theme this won't be of any help however, because especially the foreground colors simply do not look good if you just invert them.

**Comment by PyGamer0** [comment]
Ok then, I will just close the issue. Thanks
